
version: '3.3'
services:
  db:    
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:  Earth8434<full<She
      MYSQL_DATABASE: menu_app_m_development
      DB_USER: <%= ENV['DB_USERNAME'] %>
      DB_PASSWORD: <%= ENV['DB_PASSWORD'] %>  
    ports:
      - 3307:3306
    expose:
      - "3306"   
    volumes:
      - mysql_db_data_container:/var/lib/mysql
  api:
    build: ./
    #command: rails db:migrate RAILS_ENV=development
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:      
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USER: <%= ENV['DB_USERNAME'] %>
      DB_PASSWORD: <%= ENV['DB_PASSWORD'] %>  
    links:
      - db    
volumes:
  mysql_db_data_container:
    driver: local